# Generated by Django 2.0.1 on 2018-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(verbose_name='Registrar Gestion')),
            ],
            options={
                'verbose_name': 'Gestion',
                'verbose_name_plural': 'Gestiones',
                'ordering': ['gestion'],
            },
        ),
    ]
