# Generated by Django 2.0.1 on 2018-01-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=500, verbose_name='Ciclo Formativo')),
                ('gestion', models.IntegerField(verbose_name='Gestion')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['ciclo'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=500, verbose_name='Curso Formativo')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.Ciclo', verbose_name='Seleccion Ciclo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['curso'],
            },
        ),
    ]
