# Generated by Django 2.0.1 on 2018-01-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiones.Gestion', verbose_name='Gestion'),
        ),
    ]
