# Generated by Django 2.0.1 on 2018-01-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_auto_20180104_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oferta.Ciclo', verbose_name='Seleccion Ciclo'),
        ),
    ]
