# Generated by Django 2.0.1 on 2018-01-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '0002_auto_20180104_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participante', '0002_auto_20180109_1154'),
        ('oferta', '0003_auto_20180109_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oferta.Curso')),
            ],
            options={
                'verbose_name': 'Detalle Curso',
                'verbose_name_plural': 'Detalle Cursos',
                'ordering': ['curso'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Evento')),
                ('fecha', models.DateField(verbose_name='Fecha de Curso')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito Educativo')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestiones.Gestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PartEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.CharField(max_length=5000, verbose_name='Cedula de Identidad')),
                ('boleta', models.CharField(max_length=5000, verbose_name='RDA Boleta de Pago')),
                ('f_inscripcion', models.CharField(max_length=5000, verbose_name='Ficha de Inscripcion')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.Evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participante.Participante')),
            ],
            options={
                'verbose_name': 'Participante Evento',
                'verbose_name_plural': 'Participantes Eventos',
                'ordering': ['participante__apellidos', 'participante__nombres'],
            },
        ),
        migrations.AddField(
            model_name='detalle',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evento.Evento'),
        ),
    ]
