# Generated by Django 2.0.1 on 2018-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partevento',
            name='evento',
        ),
        migrations.AddField(
            model_name='partevento',
            name='detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evento.Detalle'),
        ),
    ]
